# syntax = docker/dockerfile:1-experimental
# Workaround for https://github.com/GoogleContainerTools/distroless/issues/1342
FROM golang:1.21 AS builder

RUN apt-get update && apt-get upgrade -y

WORKDIR /go/src/github.com/ory/kratos

COPY go.mod go.mod
COPY go.sum go.sum
COPY internal/httpclient/go.* internal/httpclient/
COPY internal/client-go/go.* internal/client-go/

ENV GO111MODULE on
ENV CGO_ENABLED 0

RUN go mod download

COPY . .

ARG VERSION
ARG COMMIT
ARG BUILD_DATE

RUN --mount=type=cache,target=/root/.cache/go-build go build \
  -ldflags="-X 'github.com/ory/kratos/driver/config.Version=${VERSION}' -X 'github.com/ory/kratos/driver/config.Date=${BUILD_DATE}' -X 'github.com/ory/kratos/driver/config.Commit=${COMMIT}'" \
  -o /usr/bin/kratos

#########################
FROM alpine:3.18.3

RUN apk --update upgrade && apk --no-cache --update-cache --upgrade --latest add ca-certificates

COPY --from=builder /usr/bin/kratos /usr/bin/kratos

EXPOSE 4433 4434

ENTRYPOINT ["kratos"]
CMD ["serve"]
